# render.yaml
services:
  - type: web
    name: ecommerce-backend
    env: docker
    plan: free
    autoDeploy: true
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: UPLOAD_DIR
        value: /app/uploads
